name: dropdown_button_plus
description: A new Flutter material DropdownButton package.
version: 0.0.1
homepage: https://github.com/good-good-study/dropdown_button_plus

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: